### ISSUE TITLE
Overlap of LeftNav element on demo page

### ISSUE THREAD

**Issue by eko24** [scup/atellier#15]
Hello.
Not sure if this one related to demo page or the whole project.
So, when I select `LeftNav` in the list of elements I see this overlap:
![image](https://cloud.githubusercontent.com/assets/758017/13119439/dcf91f82-d5b1-11e5-8f3a-c21f6d96b16c.png)
Warning appeared in console when I clicked on `LeftNav`:
`Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message` in `react-attelier.js:37873`
I'm using Chrome on Windows 8.

**Comment by agutoli** [comment]
Hi @eko24, I saw that LeftNav (material component) has a position absolute and is on the Atellier sidebar. About `Warning`, we will see more closely. tks for reporting...

**Comment by simplysh** [comment]
How about adding `position: relative` to the stage element. I think the stage should behave like a document view and keep everything contained.

Edit: Nevermind, I checked and the property is there but LeftNav is using actually using `position:fixed`.
