### ISSUE TITLE
Case sensitive issues with react

### ISSUE THREAD

**Issue by Neablis** [scup/atellier#17]
**Overview of the Issue -

Case sensitive issues with using require('React') instead of require('react') with webpack

ERROR in ./~/react-atellier/dist/react-atellier.min.js
Module not found: Error: Cannot resolve module 'React' in /melodis/node_websites/Soundhound-Atellier/node_modules/react-atellier/dist
 @ ./~/react-atellier/dist/react-atellier.min.js 1:82-98

**Motivation for or Use Case - 

Cant build using webpack on some systems.

**#Atellier Version(s) - 

0.0.14

**Browsers and Operating System -

Lots of warnings in OSX, will not build in Linux

**Suggest a Fix - 

Not a fix but if you manually go into /dist/react-atellier.min.js and change all instances of require('React') to require('react') it will fix it.

TBD

**Comment by andykenward** [comment]
@Neablis i added an alias in my webpack file to `React` which seemed to solve the issue for me

https://gist.github.com/andykenward/d3f88ef50d8a6628e163

**Comment by agutoli** [comment]
Hi @Neablis, we are working to fix it soon, I am sorry about that and tks for reporting...

**Comment by jasokant** [comment]
@andykenward I want to try to use your fix, but I'm not sure where your constants object is coming from?

**Comment by agutoli** [comment]
hi @Neablis, we just fix it in v0.1.9 version...
