### ISSUE TITLE
"Super expression must either be null or a function"

### ISSUE THREAD

**Issue by joerodrig** [scup/atellier#28]
Trying to test out this lib but can't seem to render the ReactAtellier component. My code and the error are below:

``` javascript
import ReactAtellier from 'react-atellier';
import TextareaAutosize from 'react-autosize-textarea';


// Surveys Index Page : Exported Component
export default class UtilitiesShowPage extends React.Component {
  render() {
    const COMPONENT_LIST = [{
      componentName: TextareaAutosize.displayName,
      component: TextareaAutosize,
    }];
    return ( <ReactAtellier components={COMPONENT_LIST}  /> );
  }
}
```

COMPONENT_LIST breaks down to:

``` javascript
COMPONENT_LIST = [{
  component: component(props, context, updater){...},
  componentName: "TextareaAutosize",
}]
```

<img width="1419" alt="screen shot 2016-03-15 at 4 43 12 pm" src="https://cloud.githubusercontent.com/assets/4582235/13793394/119f0d48-eacd-11e5-9f04-29a177e4a049.png">

**Comment by agutoli** [comment]
Hi, @joerodrig3... Do you have tried this?

`var ReactAtellier = require('react-atellier')( React );`

**Comment by joerodrig** [comment]
That fixed it, thank you :)
