### ISSUE TITLE
There is another module with an equal name when case is ignored.

### ISSUE THREAD

**Issue by theotow** [scup/atellier#29]
Hey guys,

i really like atellier, but if i embed it in my project i get a lot of these warning for various react file in webpack. Anyone has the same issue?

WARNING in ./~/React/lib/ReactDOMSelection.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

Thanks

**Comment by agutoli** [comment]
hi @theotow, we just released a version with this fix. tks!
