### ISSUE TITLE
react-atellier@0.1.11 invalid

### ISSUE THREAD

**Issue by sompylasar** [scup/atellier#46]
`npm@3.10.7` reports the `latest` published version of `react-atellier` as invalid. 

Could you please verify that it is published properly?

**Comment by agutoli** [comment]
Hi @sompylasar, I have made some tests here and it works for me... Can you show me what problem is occurring exactly?

<img width="592" alt="screen shot 2016-09-05 at 2 34 32 pm" src="https://cloud.githubusercontent.com/assets/298845/18254641/190735a6-7376-11e6-92a3-49cb6f58c3b2.png">

**Comment by sompylasar** [comment]
Looks like it somehow fixed itself.

**Comment by agutoli** [comment]
@sompylasar  I have updated README.md with you as contributor, ok? tks to help us!

**Comment by sompylasar** [comment]
@agutoli Thanks :) this product helps me as well. The best of what I've seen in this field, despite of quite a few bugs.

**Comment by sompylasar** [comment]
@agutoli by the way, there is a bug in the README:

```
- [Daniel Allegretti](https://github.com/allegretti)
- [João Neto](https://github.com/allegretti)
- [João Neto](https://github.com/joaoneto)
```

João Neto twice, the first link is wrong.

**Comment by sompylasar** [comment]
@agutoli P.S. `- [Geison](https://github.com/ojeison)` is broken as well, should likely be `- [Geison Porfirio](https://github.com/geison)`

**Comment by agutoli** [comment]
I have fixed these problems... tks!
